### ISSUE TITLE
Unable to retrieve metadata from transactions list

### ISSUE THREAD

**Issue by JoeWoodward** [omisego/ruby-sdk#11]
# Subject of the issue

When retrieving a list of transactions, I expect to be able to view the metadata associated with the transaction

# Your environment

All environments

# Steps to reproduce

```ruby
response = OmiseGO::Transaction.all
response.data.first.metadata
```

# Expected behavior

Should return metadata supplied when crediting or debiting previously

# Actual behavior

Method undefined

**Comment by T-Dnzt** [comment]
Fixed in #12. Closing :)
