### ISSUE TITLE
Passing string values to paginatable resources returns error with unhelpful description

### ISSUE THREAD

**Issue by JoeWoodward** [omisego/ruby-sdk#13]
When calling a paginatable resource and passing `page` and `per_page` params as strings, I get an error back with a less than optimal description and no messages

This is the code I have in my rails app.

```ruby
      OmiseGO::Transaction.all_for_user(
        provider_user_id: current_user.uuid,
        params: {
          page: params[:page],
          per_page: params[:per_page],
          sort_by: "created_at",
          sort_dir: "desc"
        }
      )
```
which returns
 `=> #<OmiseGO::Error:70238784066200 code: server:internal_server_error, description: argument error, messages: >`

If I cast `to_i` on `page` and `per_page` the transactions are returned as expected.

# Expected behavior

The gem should cast `to_i` and the api should return a useful message.

**Comment by JoeWoodward** [comment]
Somewhat unrelated... This `all_for_user` method seems like it should maybe not exist to me. i.e. `OmiseGO::Transaction#all` should accept `provider_user_id:` as an argument and then do the magic in the background. They are essentially the same method from the outside; they both returns a set of transactions, just based on different set of filters. Are there any limitations preventing this idea?

**Comment by T-Dnzt** [comment]
Would be nice if the Ruby SDK had a simple `.to_i` to prevent those issues, will add that. I also agree that the error messages are not the best, we can probably improve that as well in the eWallet.

Fair enough for the `all_for_user`, will update it (unless you wanna do it ;)) and deprecate it.

**Comment by T-Dnzt** [comment]
Just created a PR to handle that in the eWallet.

**Comment by T-Dnzt** [comment]
Fixed in [eWallet](https://github.com/omisego/ewallet/pull/127). Closing :)
